### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by carcinocron** [RickWong/fetch-plus#16]
Running this in node `v4.4.1`

```
'use strict';

// import {fetch, createClient} from "fetch-plus"
const dp = require('./lib/debug/dumpPromise');
const isomorphicFetch = require('isomorphic-fetch');
const fetchPlus = require('fetch-plus');
const fetch = fetchPlus.fetch;
const createClient = fetchPlus.createClient;
// import plusJson from "fetch-plus-json";
const plusJson = require('fetch-plus-json');//.plusJson;

const api = createClient("http://www.client1.com");

// Add JSON headers and response transformer.
api.addMiddleware(plusJson);

// Add custom error handler that prints and rethrows any error.
api.addMiddleware((request) => ({error: (e) => {console.warn("Rethrowing: ", e&&e.stack||e); throw e;}}));

function renderJSON (response) {
    console.log("Rendered response to screen");

    console.log(Object.keys(response));
    // console.log(JSON.stringify(response,null,4));
}
function renderError (response) {
    // console.log();

    console.log(JSON.stringify({
        '0' : "Rendered Error response to screen",
        url:response.url,
        status:response.status,
        body:((body)=>{
            if (typeof body === 'string' )
            {
                return body.slice(0,160);
            }
            // return body.read();
            // return body.toString();
            return {
                keys:          Object.keys(body),
                // prototypeKeys: Object.keys(body.prototype)
            };
        })(response.body)
    },null,4));
    console.log(Object.keys(response));
}

const attemptLoginPromise = api.request(["login"], {
    method: "POST",
    body: {
        username: "username",
        password: "password",
    }
});

attemptLoginPromise.then(renderJSON,renderError);
```

```
Rethrowing:  TypeError: Cannot read property 'headers' of undefined
    at t.before (/home/forge/www/restful/node_modules/fetch-plus-json/dist/index.js:1:707)
    at /home/forge/www/restful/node_modules/fetch-plus-json/dist/index.js:1:975
    at process._tickCallback (node.js:369:9)
```

**Comment by RickWong** [comment]
You should invoke `plusJson()` when calling `addMiddleware(...)`.
